{% set name = "piou" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Andarius/piou/archive/refs/tags/{{ version }}.tar.gz
  sha256: ec29786831491d47472ca9cd2cb39e2024e1a4579bb6913178be0539dc982043


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv >=0.7.20,<1.0
  run:
    - python >={{ python_min }},<4.0
    - rich >=10.11.0,<15.0
    - typing-extensions >=4.4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -m piou.example -h
  imports:
    - piou
about:
  home: https://github.com/Andarius/piou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CLI tool to build beautiful command-line interfaces with type validation
  dev_url: https://github.com/Andarius/piou
  doc_url: https://github.com/Andarius/piou

extra:
  recipe-maintainers:
    - andarius
