{% set name = "piou" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Andarius/piou/archive/refs/tags/{{ version }}.tar.gz
  sha256: 89b5c177862ca2db3428fde27dce9162d6bd99e965ca92f5aa010f6e346454ae


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<4.0
    - rich >=10.11.0,<15.0
    - typing-extensions >=4.4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  source_files:
    - examples/
  commands:
    - pip check
    - python -m examples -h
    - python -m examples.simple -h
    - python -m examples.derived -h
  imports:
    - piou

about:
  home: https://github.com/Andarius/piou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CLI tool to build beautiful command-line interfaces with type validation
  dev_url: https://github.com/Andarius/piou
  doc_url: https://github.com/Andarius/piou

extra:
  recipe-maintainers:
    - andarius
