{% set name = "piou" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Andarius/piou/archive/refs/tags/{{ version }}.tar.gz
  sha256: 42aaaea61b2087e8ca76dbed253b1eca895b734426838c3470c0293cd1141733


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.3.2
  run:
    - python >={{ python_min }},<4.0
    - rich >=10.11.0,<15.0
    - typing-extensions >=4.4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -m piou.example -h
  imports:
    - piou
about:
  home: https://github.com/Andarius/piou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CLI tool to build beautiful command-line interfaces with type validation
  dev_url: https://github.com/Andarius/piou
  doc_url: https://github.com/Andarius/piou

extra:
  recipe-maintainers:
    - andarius
